plugins {
    id "com.android.application"
}

def releaseKeystore = System.getenv("ANDROID_KEYSTORE_FILE")

android {
    namespace "local.voicerouter"
    compileSdk 35

    defaultConfig {
        applicationId "local.voicerouter"
        minSdk 28
        targetSdk 35
        versionCode 9
        versionName "1.8"
    }

    signingConfigs {
        release {
            if (releaseKeystore) {
                storeFile file(releaseKeystore)
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias System.getenv("ANDROID_KEY_ALIAS")
                keyPassword System.getenv("ANDROID_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            if (releaseKeystore) signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
