plugins {
    id "com.android.application"
}

android {
    namespace "local.voicerouter"
    compileSdk 35

    defaultConfig {
        applicationId "local.voicerouter"
        minSdk 28
        targetSdk 35
        versionCode 8
        versionName "1.7"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
